version: '3.1'
services:
  nagios:
    container_name: nagios4
    image: jasonrivers/nagios:latest
    restart: always
    ports:
      - 8080:80
      - 5666:5666
    volumes:
      - ./config/ssh:/opt/nagios/.ssh
      - ./config/etc/:/opt/nagios/etc/
      - ./config/var/:/opt/nagios/var/
      - ./config/plugins:/opt/Custom-Nagios-Plugins
      - ./config/apache2/nagios.conf:/etc/apache2/sites-available/nagios.conf
