version: '3.1'
services:
  nagios:
    container_name: nagios4
    image: jasonrivers/nagios:latest
    restart: always
    ports:
      - 8081:80
      - 5666:5666
    logging:
      options:
        max-size: "5m"
        max-file: "2"
    volumes:
      - ./config/ssh:/opt/nagios/.ssh
      - ./config/plugins:/opt/Custom-Nagios-Plugins
      - ./config/apache2/nagios.conf:/etc/apache2/sites-available/nagios.conf
      - ./config/graphrrd:/opt/nagiosgraph/var/rrd
      - ./config/etc/cgi.cfg:/opt/nagios/etc/cgi.cfg
      - ./config/etc/nagios.cfg:/opt/nagios/etc/nagios.cfg
      - ./config/etc/htpasswd.users:/opt/nagios/etc/htpasswd.users
      - ./config/etc/objects:/opt/nagios/etc/objects
#      - ./status.dat:/opt/nagios/var/status.dat
#      - ./config/etc/objects/localhost.cfg:/opt/nagios/etc/objects/localhost.cfg
#      - ./config/etc/objects/commands.cfg:/opt/nagios/etc/objects/commands.cfg
#      - ./config/etc/objects/contacts.cfg:/opt/nagios/etc/objects/contacts.cfg
#      - ./config/graphrrd:/opt/nagiosgraph/var/rrd

